### ISSUE TITLE
Crash on loading...

### ISSUE THREAD

**Issue by Matthww** [ImagicalCorp/AuthDataTransfer#1]
http://pastebin.com/YfmWgdRj

**Comment by Matthww** [comment]
Thanks but now it's loading and giving this message:

[15:57:20] [Server thread/CRITICAL]: [SimpleTransfer] Unable to sumbit user to MySQL Database: Unknown Error. Disabling Plugin...
[15:57:20] [Server thread/NOTICE]: [SimpleTransfer] 0 processed.
[15:57:20] [Server thread/WARNING]: RuntimeException: "yaml_parse(): end of stream reached without finding document 0" (E_WARNING) in "/src/pocketmine/utils/Config" at line 143
[15:57:20]

spamming...

Thanks for helping btw :)

**Comment by Matthww** [comment]
I really need this because i have like a million of registered people and my laptop just crashes when i ftp into it!

**Comment by k3ithos** [comment]
There's something incorrect in the config file. Please check how you should use .yml files if you need more info.

**Comment by Matthww** [comment]
---

#Server IP for MySQL. Defaults to localhost
server-name: 192.168.1.109
#Username to login
username: SimpleAuth
#Password for MySQL Database
password: (censored)
#The SimpleAuth MySQL database name (Create one first)
simpleauth-dbname: SimpleAuth
#Port to connect to MySQL. Defaults to 3306
port: 3306
...

This is what my config looks like

**Comment by Matthww** [comment]
I setted my debug level to 3 and i get this:

http://pastebin.com/ssa5WH2M

**Comment by legoboy0215** [comment]
Ok. I gonna fix it today.

**Comment by Matthww** [comment]
Thank you!!!

**Comment by Matthww** [comment]
After the commit 'lol' i still get the same error...

**Comment by legoboy0215** [comment]
No that is a useless commit :P

**Comment by k3ithos** [comment]
LOL

**Comment by Matthww** [comment]
oh xD

**Comment by Matthww** [comment]
Do you already know how to fix it?

**Comment by Matthww** [comment]
Is this project dead? Or are you too busy?

**Comment by Matthww** [comment]
So i managed to fix it i manually maded the tables and it worked but now i get this after 6300 files:

http://pastebin.com/5nyKNbw9

**Comment by Matthww** [comment]
It only happens when a .yml file is empty

**Comment by legoboy0215** [comment]
I am busy. Ill try and fix. can u give me 10 sample player files?

**Comment by Matthww** [comment]
Lego everything works i will make a tutorial soon for you

**Comment by legoboy0215** [comment]
REALLY?

**Comment by k3ithos** [comment]
Nice! XD

**Comment by Matthww** [comment]
Made a PR
