### ISSUE TITLE
PLEASE HELP!!! I need it right now!

### ISSUE THREAD

**Issue by alex2534alex** [ImagicalCorp/AuthDataTransfer#5]
[08:48:01] [INFO]: Loading source plugin SimpleTransfer v1.0.0
[08:48:01] [WARNING]: RuntimeException: "mysqli::mysqli(): (HY000/2002): No such file or directory" (E_WARNING) in "/plugins/TRANS/src/Legoboy/ST/Loader" at line 17

**Comment by alex2534alex** [comment]
@legoboy0215 , can u fix that?

**Comment by legoboy0215** [comment]
http://stackoverflow.com/questions/1676688/php-mysql-connection-not-working-2002-no-such-file-or-directory

**Comment by alex2534alex** [comment]
Add that situation to ReadMe

**Comment by alex2534alex** [comment]
@legoboy0215 , don't working((
![screenshot_2016-02-20-08-22-43](https://cloud.githubusercontent.com/assets/15706847/13194935/5027b91e-d7ab-11e5-83cb-c09a72ff49b6.png)

**Comment by alex2534alex** [comment]
I added a line because it did not exist

**Comment by k3ithos** [comment]
Maybe you should try reinstalling PHP with mysqli and MySQL support...

**Comment by alex2534alex** [comment]
How?

**Comment by alex2534alex** [comment]
Where I can find PHP binary with support of MySQL?
P.S.: @keithkfng , I use your (ImagicalMine) PHP5-x64 binary -_-

**Comment by legoboy0215** [comment]
Oh. Setup your MySQL server better.

**Comment by alex2534alex** [comment]
??
